### ISSUE TITLE
Create Release task triggers Deployment

### ISSUE THREAD

**Issue by rohmcd** [OctopusDeploy/Octopus-Bamboo#1]
I have used the add-on and added the following tasks to my job:
Pack Package
Push Package
Create Release

But when the plan runs, it is automatically deploying my project! 

I do not have any automatic deployment triggers set up, all i want is a new release ready for deployment. 

it may be related, but the descriptions on the tasks are duplicated as well.
![image](https://user-images.githubusercontent.com/773017/28198484-db561d5e-68a1-11e7-98b2-3b75966deea3.png)

**Comment by vanessalove** [comment]
Hi @rohmcd, thanks for getting in touch with us. The best way to work through this is to use our support channel: http://octopus.com/support
We don't actively monitor this backlog for new issues.
Looking forward to helping you sort out what's going wrong.
