### ISSUE TITLE
Package metadata step on remote agent fails to find the `administrationConfiguration` module

### ISSUE THREAD

**Issue by hnrkndrssn** [OctopusDeploy/Octopus-Bamboo#6]
Source ticket: https://help.octopus.com/t/error-while-using-octopus-metadata-plugin-in-bamboo/23140

**Comment by bogdangrigg** [comment]
@slewis74 It would be very valuable to have this, as we're using the Bamboo plugin exclusively on remote agents. Would it be possible to release a new build on the Atlassian Marketplace?
